backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "业务"
    name: "services"
    delete: false
    editor:
      preview: false
    files:
      - name: "indoor"
        label: "室内业务"
        file: "src/data/services/indoor.yml"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - label: "子项目"
            name: "sub_items"
            required: false
            widget: "list"

      - name: "outdoor"
        label: "屋外业务"
        file: "src/data/services/outdoor.yml"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - label: "子项目"
            name: "sub_items"
            required: false
            widget: "list"
            default: [""]
