backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "indoor_service"
    label: "Indoor Service"
    folder: "src/data/services"
    filter: {field: "category", value: "indoor"}
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "category", name: "category", widget: "hidden", default: "indoor"}
      - {label: "Thumbnail", name: "image", widget: "image", default: "http://via.placeholder.com/1290x720"}
      - label: "Sub-Services"
        name: "sub_services"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
  - name: "outdoor_service"
    label: "Outdoor Service"
    folder: "src/data/services"
    filter: {field: "category", value: "outdoor"}
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "category", name: "category", widget: "hidden", default: "outdoor"}
      - {label: "Thumbnail", name: "image", widget: "image"}
      - label: "Sub-Services"
        name: "sub_services"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
