backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "业务"
    name: "services"
    delete: false
    editor:
      preview: false
    files:
      - name: "indoor"
        label: "室内业务"
        file: "src/data/services/indoor.yml"
        fields:
          - name: "services"
            label: "Services"
            label_singular: "Service"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: false}
              - name: "sub_items"
                label: "Sub Items"
                widget: "list"
                required: false
      - name: "outdoor"
        label: "屋外业务"
        file: "src/data/services/outdoor.yml"
        fields:
          - name: "services"
            label: "Services"
            label_singular: "Service"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: false}
              - name: "sub_items"
                label: "Sub Items"
                widget: "list"
                required: false
