backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "室内业务"
    name: "indoor_services"
    folder: "src/data/services"
    extension: "yml"
    create: true
    filter: {field: "category", value: "indoor"}
    fields:
      - {label: "Category", name: "category", widget: "hidden", default: "indoor"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - name: "sub_items"
        label: "子项目"
        widget: "list"
        required: "false"
  - label: "屋外业务"
    name: "outdoor_services"
    folder: "src/data/services"
    extension: "yml"
    create: true
    filter: {field: "category", value: "outdoor"}
    fields:
      - {label: "Category", name: "category", widget: "hidden", default: "outdoor"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - name: "sub_items"
        label: "子项目"
        widget: "list"
        required: "false"
