backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Page"
    name: "page"
    delete: false
    files:
      - label: "着陆页"
        name: "landing_page"
        file: "src/pages/index.md"
        fields:
          # Section - Hero
          - {label: "宣传语", name: "tagline"}
          - {label: "价值主张", name: "value_proposition", widget: "text"}

          # CTA
          # - label: "Call To Action (行为召唤)"
          #   name: "cta"
          #   widget: "list"
          #   fields:
          #     - {label: "文字", name: "text"}
          #     - {label: "类型", name: "type", widget: "select", options: ["页内导航", "站内导航"]}
          #     - {label: "链接目的地", name: "target"}

          # Section - About Us
          - {label: "关于我们 - 标题", name: "AboutUs_title"}
          - {label: "关于我们 - 描述", name: "AboutUs_summary", widget: "text"}
          - label: "专栏"
            name: "columns"
            widget: "list"
            fields:
              - {label: "内容", name: "content", widget: "markdown"}
          # Section - services
          - {label: "业务范围 - 标题", name: "Services_title", required: false}
          - label: "业务类型"
            name: "categories"
            widget: "list"
            fields:
              - {label: "名称", name: "name"}
              - {label: "图片", name: "image", widget: "image"}
              - {label: "标签", name: "tags", widget: "list"}

  - label: "项目"
    name: "service"
    create: true
    folder: "src/data/services"
    fields:
      - {label: "名称", name: "title", widget: "string"}
      - {label: "图片", name: "image", widget: "image"}
      - {label: "子项目", name: "sub_items", widget: "list", required: "false"}
      - label: "类别"
        name: "category"
        widget: "select"
        options:
          - {label: "室内业务", value: "0"}
          - {label: "户外业务", value: "1"}
