backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "内容"
    name: "content"
    delete: false
    files:
      - label: "着陆页"
        name: "landing_page"
        file: "src/data/index.md"
        fields:
          # Section - Hero
          - {label: "宣传语", name: "tagline"}
          - {label: "价值主张", name: "value_proposition", widget: "text"}
          - {label: "背景图片", name: "background_image", widget: "image"}

          # Section - About Us
          - {label: "关于我们 - 标题", name: "AboutUs_title", required: false}
          - {label: "关于我们 - 描述", name: "AboutUs_summary", widget: "text",required: false}

          # Section - services
          - {label: "业务范围 - 标题", name: "Services_title", required: false}

          # Footer
          - {label: "联系我们", name: "ContactUs", widget: "markdown", required: false}

  - label: "业务类型"
    name: "categories"
    create: true
    folder: "src/data/categories"
    fields:
      - {label: "名称", name: "name"}
      - {label: "图片", name: "thumbnail", widget: "image"}
      - {label: "标签", name: "tags", widget: "list"}

  - label: "专栏"
    name: "columns"
    create: true
    folder: "src/data/columns"
    fields:
      - {label: "标题", name: "heading"}
      - {label: "段落", name: "paragraph", widget: "text"}
      - {label: "图片", name: "thumbnail", widget: "image"}

  - label: "项目"
    name: "service"
    create: true
    folder: "src/data/services"
    fields:
      - {label: "名称", name: "title", widget: "string"}
      - {label: "图片", name: "thumbnail", widget: "image"}
      - {label: "子项目", name: "sub_items", widget: "list", required: "false"}
      - label: "类别"
        name: "category"
        widget: "select"
        options:
          - {label: "室内业务", value: "0"}
          - {label: "户外业务", value: "1"}
