backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "主页"
    name: "index"
    delete: false
    editor:
      preview: false
    files:
      - label: "About"
        name: "about"
        file: "src/data/content/about.md"
        fields:
          - {label: "Title", name: "title"}
          - {label: "Summary", name: "summary"}
          - label: "Columns"
            name: "columns"
            widget: "list"
            fields:
              - {label: "Title", name: "title"}
              - {label: "Image", name: "image"}
              - {label: "Text", name: "text", widget: "text"}
  - label: "业务"
    name: "services"
    delete: false
    files:
      - label: "室内业务"
        name: "indoor_services"
        file: "src/data/services/indoor.md"
        fields:
          - {label: "类别", name: "category"}
          - {label: "标签", name: "tags", widget: "list"}
          - label: "项目"
            name: "services"
            widget: "list"
            fields:
              - {label: "名称", name: "title", widget: "string"}
              - {label: "图片", name: "image", widget: "image"}
              - {name: "sub_items",label: "子项目",  widget: "list", required: "false"}
      - label: "屋外业务"
        name: "outdoor_services"
        file: "src/data/services/outdoor.md"
        fields:
          - {label: "类别", name: "category"}
          - {label: "标签", name: "tags", widget: "list"}
          - label: "项目"
            name: "services"
            widget: "list"
            fields:
              - {label: "名称", name: "title", widget: "string"}
              - {label: "图片", name: "image", widget: "image"}
              - {name: "sub_items",label: "子项目",  widget: "list", required: "false"}
