backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "业务"
    name: "services"
    extension: "yml"
    files:
      - label: "室内业务"
        name: "indoor_services"
        file: "src/data/services/indoor.yml"
        delete: false
        fields:
          - label: "室内业务"
            name: "services"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "图片"
                name: "image"
                widget: "image"
                default: "http://via.placeholder.com/1280x720"
              - name: "sub_items"
                label: "子项目"
                widget: "list"
                required: "false"
      - label: "屋外业务"
        name: "outdoor_services"
        file: "src/data/services/outdoor.yml"
        delete: false
        fields:
          - label: "屋外业务"
            name: "services"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "图片"
                name: "image"
                widget: "image"
                default: "http://via.placeholder.com/1280x720"
              - name: "sub_items"
                label: "子项目"
                widget: "list"
                required: "false"
